In [2]:
import pandas as pd
filepath = "laptop_pricing_dataset_mod1.csv"
df = pd.read_csv(filepath)

In [27]:
df.head(5)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837

In [28]:
import numpy as np
df.replace('?',np.nan)
df

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,233,Lenovo,4,IPS Panel,2,1,7,35.560,2.6,8,256,1.70,1891
234,234,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.20,1950
235,235,Lenovo,4,IPS Panel,2,1,5,30.480,2.6,8,256,1.36,2236
236,236,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.40,883
237,237,Toshiba,3,Full HD,2,1,5,35.560,2.3,8,256,1.95,1499

In [7]:
missing_data= df.isnull()
missing_data.head(5)

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False

In [29]:
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

Unnamed: 0
Unnamed: 0
False    238
Name: count, dtype: int64

Manufacturer
Manufacturer
False    238
Name: count, dtype: int64

Category
Category
False    238
Name: count, dtype: int64

Screen
Screen
False    238
Name: count, dtype: int64

GPU
GPU
False    238
Name: count, dtype: int64

OS
OS
False    238
Name: count, dtype: int64

CPU_core
CPU_core
False    238
Name: count, dtype: int64

Screen_Size_cm
Screen_Size_cm
False    234
True       4
Name: count, dtype: int64

CPU_frequency
CPU_frequency
False    238
Name: count, dtype: int64

RAM_GB
RAM_GB
False    238
Name: count, dtype: int64

Storage_GB_SSD
Storage_GB_SSD
False    238
Name: count, dtype: int64

Weight_kg
Weight_kg
False    233
True       5
Name: count, dtype: int64

Price
Price
False    238
Name: count, dtype: int64

In [9]:
avg_weight_kg=df["Weight_kg"].astype("float").mean(axis=0)
print("Avergae of weitght in kg:", avg_weight_kg)

Avergae of weitght in kg: 1.8622317596566522

In [30]:
import numpy as np
df["Weight_kg"].replace(np.nan, avg_weight_kg)

0      1.60
1      2.20
2      2.20
3      1.22
4      1.91
       ...
233    1.70
234    1.20
235    1.36
236    2.40
237    1.95
Name: Weight_kg, Length: 238, dtype: float64

In [31]:
common_screen_size = df['Screen_Size_cm'].value_counts().idxmax()
df['Screen_Size_cm']= df['Screen_Size_cm'].replace(np.nan,common_screen_size)
df['Screen_Size_cm']
df

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_cm,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price
0,0,Acer,4,IPS Panel,2,1,5,35.560,1.6,8,256,1.60,978
1,1,Dell,3,Full HD,1,1,3,39.624,2.0,4,256,2.20,634
2,2,Dell,3,Full HD,1,1,7,39.624,2.7,8,256,2.20,946
3,3,Dell,4,IPS Panel,2,1,5,33.782,1.6,8,128,1.22,1244
4,4,HP,4,Full HD,2,1,7,39.624,1.8,8,256,1.91,837
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,233,Lenovo,4,IPS Panel,2,1,7,35.560,2.6,8,256,1.70,1891
234,234,Toshiba,3,Full HD,2,1,5,33.782,2.4,8,256,1.20,1950
235,235,Lenovo,4,IPS Panel,2,1,5,30.480,2.6,8,256,1.36,2236
236,236,Lenovo,3,Full HD,3,1,5,39.624,2.5,6,256,2.40,883
237,237,Toshiba,3,Full HD,2,1,5,35.560,2.3,8,256,1.95,1499

In [32]:
df.dtypes

Unnamed: 0          int64
Manufacturer       object
Category            int64
Screen             object
GPU                 int64
OS                  int64
CPU_core            int64
Screen_Size_cm    float64
CPU_frequency     float64
RAM_GB              int64
Storage_GB_SSD      int64
Weight_kg         float64
Price               int64
dtype: object

In [47]:
df['Weight_kg']= df["Weight_kg"]* 2.205
df.rename(columns={'Weight_kg':'Weight_pounds'})

,Unnamed: 0,Manufacturer,Category,Screen,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_pounds,Price
0,0,Acer,4,IPS Panel,2,1,5,14.0,1.6,8,256,37.822859,978
1,1,Dell,3,Full HD,1,1,3,15.6,2.0,4,256,52.006432,634
2,2,Dell,3,Full HD,1,1,7,15.6,2.7,8,256,52.006432,946
3,3,Dell,4,IPS Panel,2,1,5,13.3,1.6,8,128,28.839930,1244
4,4,HP,4,Full HD,2,1,7,15.6,1.8,8,256,45.151038,837
...,...,...,...,...,...,...,...,...,...,...,...,...,...
233,233,Lenovo,4,IPS Panel,2,1,7,14.0,2.6,8,256,40.186788,1891
234,234,Toshiba,3,Full HD,2,1,5,13.3,2.4,8,256,28.367145,1950
235,235,Lenovo,4,IPS Panel,2,1,5,12.0,2.6,8,256,32.149430,2236
236,236,Lenovo,3,Full HD,3,1,5,15.6,2.5,6,256,56.734289,883
237,237,Toshiba,3,Full HD,2,1,5,14.0,2.3,8,256,46.096610,1499

In [4]:
df['Screen_Size_cm']= df['Screen_Size_cm'] /2.54
df.rename(columns={'Screen_Size_cm':'Screen_Size_inch'}, inplace =True)

KeyError: 'Screen_Size_cm'

## normalization

In [5]:
df[['CPU_frequency']]=df[['CPU_frequency']]/df['CPU_frequency'].max()

# binning

In [6]:
df['Price']=df['Price'].astype('float')

In [7]:
import numpy as np
bins=np.linspace(min(df['Price']),max(df["Price"]),4)
bins

array([ 527.        , 1621.33333333, 2715.66666667, 3810.        ])

In [8]:
group_names = ['Low','Medium', 'High']

In [9]:
df['Price-binned']= pd.cut(df['Price'],bins,labels=group_names, include_lowest=True)
df[['Price','Price-binned']].head(20)

     Price Price-binned
0    978.0          Low
1    634.0          Low
2    946.0          Low
3   1244.0          Low
4    837.0          Low
5   1016.0          Low
6   1117.0          Low
7    866.0          Low
8    812.0          Low
9   1068.0          Low
10   975.0          Low
11   558.0          Low
12   527.0          Low
13  1117.0          Low
14  1195.0          Low
15   876.0          Low
16  1213.0          Low
17  1105.0          Low
18  1392.0          Low
19  1092.0          Low

In [10]:
dummy_variable_1=pd.get_dummies(df["Screen"])
dummy_variable_1.head()

   Full HD  IPS Panel
0    False       True
1     True      False
2     True      False
3    False       True
4     True      False

In [11]:
dummy_variable_1.rename(columns={'Full HD':'Screen-Full_HD','IPS Panel':'Screen-IPS_panel'},inplace= True)
dummy_variable_1.head()

   Screen-Full_HD  Screen-IPS_panel
0           False              True
1            True             False
2            True             False
3           False              True
4            True             False

In [12]:
df= pd.concat([df, dummy_variable_1], axis =1)

df.drop("Screen", axis =1, inplace = True)
df.head()

,Unnamed: 0,Manufacturer,Category,GPU,OS,CPU_core,Screen_Size_inch,CPU_frequency,RAM_GB,Storage_GB_SSD,Weight_kg,Price,Price-binned,Screen-Full_HD,Screen-IPS_panel
0,0,Acer,4,2,1,5,14.0,0.551724,8,256,1.60,978.0,Low,False,True
1,1,Dell,3,1,1,3,15.6,0.689655,4,256,2.20,634.0,Low,True,False
2,2,Dell,3,1,1,7,15.6,0.931034,8,256,2.20,946.0,Low,True,False
3,3,Dell,4,2,1,5,13.3,0.551724,8,128,1.22,1244.0,Low,False,True
4,4,HP,4,2,1,7,15.6,0.620690,8,256,1.91,837.0,Low,True,False